### ISSUE TITLE
Add a "Deploy to Heroku" badge to the README

### ISSUE THREAD

**Issue by raisedhand** [SuperSonicHub1/witch#1]
hi kyle ,
please if it's possible make deploy to heroku button for free of monthly vps charge. also heroku have any buildpack you need like selenium , chrome headless , ffmpeg , or ...
waiting for your response
finest regards

**Comment by SuperSonicHub1** [comment]
First of all, thank you for showing interest in my little project; I'm super glad you find it useful enough to want to deploy it! 

I've had plans for quite a while to get Witch up and running on Replit, Heroku, Docker and other platforms, but I'm still in the thick of development and so haven't spent a long time thinking about that. I haven't used Heroku to deploy a Flask app in what will soon be nine months, but I'll try to get around to it ASAP. It shouldn't be that hard, since Witch uses Poetry and doesn't rely on any external binaries.

**Comment by SuperSonicHub1** [comment]
It is done! Please see `new-branch` for the Procfile!
https://witch-video.herokuapp.com/
Now to add a README.

**Comment by SuperSonicHub1** [comment]
It is done! Please see `new-branch` for the Procfile!
https://witch-video.herokuapp.com/
Now to add a README.

**Comment by SuperSonicHub1** [comment]
Now there's a deploy button on the README!
https://heroku.com/deploy?template=https://github.com/supersonichub1/witch/tree/new-branch

**Comment by SuperSonicHub1** [comment]
If it works perfectly for you, close the issue!

**Comment by SuperSonicHub1** [comment]
If it works perfectly for you, close the issue!

**Comment by raisedhand** [comment]
hello again kyle , 
after deployed using your deploy to heroku button exist on new branch , some features needed & some changes required :
1 - Search: field isn't work.
2 - live stream ui is not mobile browser friendly.
3 - please add embed button for can show on my own site .
waiting for your commits on new branch :)
finest regards

**Comment by SuperSonicHub1** [comment]
Cool, I'm already aware of all these issues:

- Search as a feature hasn't been implemented yet. The form on the homepage
is simply a placeholder.
- My current focus is function over form and not making the desktop
experience look awful. I'll eventually come back around to mobile devices
soon enough.
- I'll be sure to add links to embeds on streams, videos, and clips soon
enough.


Could you please create new issues for each of these instead of reopening
this one?
